[project]
name = "probikegarage-to-sqlite"
version = "0.1.0"
description = "Download ProBikeGarage data for analysis and backup purposes."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "typer>=0.21.1",
    "datasette>=0.65.2",
    "httpx>=0.28.1",
    "sqlite-utils>=3.39",
]
